import { Injectable } from '@angular/core';
import { Product } from '../model/product';

@Injectable({
  providedIn: 'root',
})
export class ProductService {
  list: Product[] = [
    {
      id: 1,
      catId: 1,
      name: 'Rigid Didymodon Moss',
      description: 'morbi ut odio cras mi pede',
      image: 'http://dummyimage.com/108x100.png/ff4444/ffffff',
      price: 33,
      stock: 8,
      featured: false,
      active: false,
    },
    {
      id: 2,
      catId: 1,
      name: 'Cape Thompson Draba',
      description: 'accumsan tellus nisi eu orci',
      image: 'http://dummyimage.com/228x100.png/cc0000/ffffff',
      price: 55,
      stock: 8,
      featured: true,
      active: true,
    },
    {
      id: 3,
      catId: 4,
      name: 'Hopea',
      description: 'sapien ut nunc vestibulum ante ipsum primis',
      image: 'http://dummyimage.com/130x100.png/cc0000/ffffff',
      price: 67,
      stock: 13,
      featured: true,
      active: true,
    },
    {
      id: 4,
      catId: 1,
      name: "Parish's Eryngo",
      description: 'at velit eu est congue',
      image: 'http://dummyimage.com/101x100.png/ff4444/ffffff',
      price: 44,
      stock: 22,
      featured: true,
      active: false,
    },
    {
      id: 5,
      catId: 1,
      name: 'Jackson Hole Thistle',
      description: 'pede justo lacinia eget tincidunt',
      image: 'http://dummyimage.com/155x100.png/5fa2dd/ffffff',
      price: 38,
      stock: 12,
      featured: true,
      active: true,
    },
    {
      id: 6,
      catId: 3,
      name: 'Senita Cactus',
      description: 'donec semper sapien a libero nam',
      image: 'http://dummyimage.com/205x100.png/ff4444/ffffff',
      price: 11,
      stock: 27,
      featured: true,
      active: true,
    },
    {
      id: 7,
      catId: 1,
      name: 'Cup Lichen',
      description: 'consequat in consequat ut nulla',
      image: 'http://dummyimage.com/162x100.png/5fa2dd/ffffff',
      price: 37,
      stock: 49,
      featured: false,
      active: true,
    },
    {
      id: 8,
      catId: 3,
      name: 'Showy Penstemon',
      description: 'quis orci nullam molestie',
      image: 'http://dummyimage.com/126x100.png/dddddd/000000',
      price: 51,
      stock: 48,
      featured: true,
      active: true,
    },
    {
      id: 9,
      catId: 2,
      name: 'Subalpine Larch',
      description: 'faucibus orci luctus et',
      image: 'http://dummyimage.com/107x100.png/5fa2dd/ffffff',
      price: 30,
      stock: 13,
      featured: true,
      active: true,
    },
    {
      id: 10,
      catId: 2,
      name: 'Maryland Meadowbeauty',
      description: 'condimentum id luctus nec molestie sed',
      image: 'http://dummyimage.com/131x100.png/cc0000/ffffff',
      price: 11,
      stock: 18,
      featured: false,
      active: false,
    },
    {
      id: 11,
      catId: 2,
      name: 'Tropidia',
      description: 'nisl duis ac nibh fusce lacus purus',
      image: 'http://dummyimage.com/201x100.png/5fa2dd/ffffff',
      price: 23,
      stock: 26,
      featured: true,
      active: true,
    },
    {
      id: 12,
      catId: 3,
      name: "Rehman's Halfchaff Sedge",
      description: 'dictumst etiam faucibus cursus',
      image: 'http://dummyimage.com/114x100.png/5fa2dd/ffffff',
      price: 76,
      stock: 3,
      featured: true,
      active: false,
    },
    {
      id: 13,
      catId: 4,
      name: 'Distichium Moss',
      description: 'dis parturient montes nascetur ridiculus mus',
      image: 'http://dummyimage.com/178x100.png/ff4444/ffffff',
      price: 54,
      stock: 6,
      featured: false,
      active: false,
    },
    {
      id: 14,
      catId: 1,
      name: 'Butte Desertparsley',
      description: 'dignissim vestibulum vestibulum ante ipsum primis in',
      image: 'http://dummyimage.com/246x100.png/5fa2dd/ffffff',
      price: 46,
      stock: 35,
      featured: false,
      active: false,
    },
    {
      id: 15,
      catId: 3,
      name: "Thurber's Fescue",
      description: 'curabitur gravida nisi at nibh in hac',
      image: 'http://dummyimage.com/152x100.png/cc0000/ffffff',
      price: 62,
      stock: 39,
      featured: true,
      active: true,
    },
    {
      id: 16,
      catId: 3,
      name: 'Mojave Sandwort',
      description: 'magna ac consequat metus sapien ut',
      image: 'http://dummyimage.com/160x100.png/cc0000/ffffff',
      price: 17,
      stock: 35,
      featured: false,
      active: false,
    },
    {
      id: 17,
      catId: 3,
      name: 'Syrian Cephalaria',
      description: 'nascetur ridiculus mus vivamus vestibulum',
      image: 'http://dummyimage.com/133x100.png/cc0000/ffffff',
      price: 74,
      stock: 23,
      featured: false,
      active: false,
    },
    {
      id: 18,
      catId: 4,
      name: 'Cissus',
      description: 'in blandit ultrices enim lorem ipsum dolor',
      image: 'http://dummyimage.com/110x100.png/5fa2dd/ffffff',
      price: 25,
      stock: 40,
      featured: true,
      active: true,
    },
    {
      id: 19,
      catId: 4,
      name: 'Bushy Blazingstar',
      description: 'eget eleifend luctus ultricies eu',
      image: 'http://dummyimage.com/246x100.png/cc0000/ffffff',
      price: 38,
      stock: 25,
      featured: false,
      active: false,
    },
    {
      id: 20,
      catId: 1,
      name: 'Seaside Joyweed',
      description: 'lorem id ligula suspendisse ornare consequat',
      image: 'http://dummyimage.com/213x100.png/dddddd/000000',
      price: 76,
      stock: 13,
      featured: true,
      active: false,
    },
    {
      id: 21,
      catId: 4,
      name: 'Hollyberry Cotoneaster',
      description: 'neque duis bibendum morbi non quam',
      image: 'http://dummyimage.com/165x100.png/ff4444/ffffff',
      price: 40,
      stock: 42,
      featured: false,
      active: true,
    },
    {
      id: 22,
      catId: 2,
      name: 'Buffelgrass',
      description: 'pede ac diam cras pellentesque volutpat',
      image: 'http://dummyimage.com/162x100.png/5fa2dd/ffffff',
      price: 31,
      stock: 24,
      featured: false,
      active: true,
    },
    {
      id: 23,
      catId: 1,
      name: 'Springflowering Goldenrod',
      description: 'vulputate elementum nullam varius',
      image: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
      price: 68,
      stock: 7,
      featured: true,
      active: true,
    },
    {
      id: 24,
      catId: 2,
      name: 'Cascade Onion',
      description: 'pulvinar lobortis est phasellus sit amet erat',
      image: 'http://dummyimage.com/244x100.png/dddddd/000000',
      price: 51,
      stock: 48,
      featured: true,
      active: true,
    },
    {
      id: 25,
      catId: 4,
      name: 'Mountain Bush Honeysuckle',
      description: 'vulputate vitae nisl aenean',
      image: 'http://dummyimage.com/118x100.png/cc0000/ffffff',
      price: 24,
      stock: 40,
      featured: true,
      active: true,
    },
    {
      id: 26,
      catId: 3,
      name: 'Gray Sheoak',
      description: 'cursus urna ut tellus nulla',
      image: 'http://dummyimage.com/101x100.png/5fa2dd/ffffff',
      price: 62,
      stock: 39,
      featured: false,
      active: true,
    },
    {
      id: 27,
      catId: 2,
      name: 'Cutleaf Silverpuffs',
      description: 'vestibulum ac est lacinia nisi venenatis tristique',
      image: 'http://dummyimage.com/204x100.png/5fa2dd/ffffff',
      price: 56,
      stock: 42,
      featured: false,
      active: true,
    },
    {
      id: 28,
      catId: 2,
      name: 'Tuftedstem Rush',
      description: 'scelerisque mauris sit amet',
      image: 'http://dummyimage.com/197x100.png/5fa2dd/ffffff',
      price: 80,
      stock: 42,
      featured: true,
      active: false,
    },
    {
      id: 29,
      catId: 2,
      name: 'Sphagnum',
      description: 'et magnis dis parturient montes nascetur',
      image: 'http://dummyimage.com/165x100.png/cc0000/ffffff',
      price: 24,
      stock: 27,
      featured: false,
      active: false,
    },
    {
      id: 30,
      catId: 1,
      name: 'Common Snowberry',
      description: 'donec diam neque vestibulum eget vulputate ut',
      image: 'http://dummyimage.com/140x100.png/5fa2dd/ffffff',
      price: 53,
      stock: 20,
      featured: true,
      active: true,
    },
    {
      id: 31,
      catId: 1,
      name: 'Kamanomano',
      description: 'mi sit amet lobortis sapien sapien non',
      image: 'http://dummyimage.com/178x100.png/5fa2dd/ffffff',
      price: 11,
      stock: 33,
      featured: false,
      active: false,
    },
    {
      id: 32,
      catId: 3,
      name: 'Dwarf Sand Verbena',
      description: 'auctor sed tristique in tempus sit amet',
      image: 'http://dummyimage.com/196x100.png/cc0000/ffffff',
      price: 67,
      stock: 43,
      featured: false,
      active: true,
    },
    {
      id: 33,
      catId: 3,
      name: 'Disc Lichen',
      description: 'cum sociis natoque penatibus et magnis dis',
      image: 'http://dummyimage.com/144x100.png/dddddd/000000',
      price: 76,
      stock: 26,
      featured: true,
      active: true,
    },
    {
      id: 34,
      catId: 4,
      name: 'Cyrtandra',
      description: 'massa id lobortis convallis tortor risus dapibus',
      image: 'http://dummyimage.com/239x100.png/5fa2dd/ffffff',
      price: 15,
      stock: 4,
      featured: false,
      active: false,
    },
    {
      id: 35,
      catId: 2,
      name: 'Monstera',
      description: 'aliquet massa id lobortis convallis',
      image: 'http://dummyimage.com/133x100.png/cc0000/ffffff',
      price: 74,
      stock: 13,
      featured: false,
      active: true,
    },
    {
      id: 36,
      catId: 4,
      name: 'Paradox Lupine',
      description: 'consequat ut nulla sed',
      image: 'http://dummyimage.com/243x100.png/cc0000/ffffff',
      price: 11,
      stock: 9,
      featured: true,
      active: false,
    },
    {
      id: 37,
      catId: 4,
      name: 'Bloodroot',
      description: 'suscipit a feugiat et eros vestibulum',
      image: 'http://dummyimage.com/106x100.png/cc0000/ffffff',
      price: 70,
      stock: 22,
      featured: false,
      active: true,
    },
    {
      id: 38,
      catId: 2,
      name: 'Oldfield Grass',
      description: 'lectus aliquam sit amet diam in',
      image: 'http://dummyimage.com/161x100.png/cc0000/ffffff',
      price: 66,
      stock: 20,
      featured: true,
      active: true,
    },
    {
      id: 39,
      catId: 4,
      name: "Wright's Flowering Fern",
      description: 'primis in faucibus orci luctus et',
      image: 'http://dummyimage.com/232x100.png/5fa2dd/ffffff',
      price: 62,
      stock: 14,
      featured: false,
      active: false,
    },
    {
      id: 40,
      catId: 2,
      name: 'West Virginia Dewberry',
      description: 'lorem quisque ut erat curabitur gravida nisi',
      image: 'http://dummyimage.com/125x100.png/dddddd/000000',
      price: 76,
      stock: 29,
      featured: false,
      active: true,
    },
    {
      id: 41,
      catId: 1,
      name: 'Climbing Cactus',
      description: 'eu est congue elementum in hac',
      image: 'http://dummyimage.com/143x100.png/cc0000/ffffff',
      price: 61,
      stock: 12,
      featured: true,
      active: false,
    },
    {
      id: 42,
      catId: 4,
      name: 'Purple Sage',
      description: 'pretium iaculis justo in',
      image: 'http://dummyimage.com/183x100.png/cc0000/ffffff',
      price: 35,
      stock: 13,
      featured: true,
      active: true,
    },
    {
      id: 43,
      catId: 4,
      name: 'Slender Goldentop',
      description: 'eu orci mauris lacinia',
      image: 'http://dummyimage.com/238x100.png/ff4444/ffffff',
      price: 74,
      stock: 32,
      featured: true,
      active: true,
    },
    {
      id: 44,
      catId: 1,
      name: 'Pinkladies',
      description: 'consequat nulla nisl nunc',
      image: 'http://dummyimage.com/134x100.png/5fa2dd/ffffff',
      price: 47,
      stock: 15,
      featured: false,
      active: true,
    },
    {
      id: 45,
      catId: 2,
      name: 'White Meadowfoam',
      description: 'hac habitasse platea dictumst etiam faucibus cursus',
      image: 'http://dummyimage.com/138x100.png/cc0000/ffffff',
      price: 20,
      stock: 16,
      featured: true,
      active: false,
    },
    {
      id: 46,
      catId: 2,
      name: 'Fivewing Spiderling',
      description: 'non lectus aliquam sit amet diam in',
      image: 'http://dummyimage.com/124x100.png/5fa2dd/ffffff',
      price: 32,
      stock: 16,
      featured: false,
      active: true,
    },
    {
      id: 47,
      catId: 1,
      name: 'Wild Garlic',
      description: 'sem mauris laoreet ut rhoncus aliquet',
      image: 'http://dummyimage.com/203x100.png/dddddd/000000',
      price: 68,
      stock: 25,
      featured: true,
      active: true,
    },
    {
      id: 48,
      catId: 1,
      name: 'Kamchatka Rhododendron',
      description: 'luctus ultricies eu nibh quisque id',
      image: 'http://dummyimage.com/229x100.png/5fa2dd/ffffff',
      price: 69,
      stock: 29,
      featured: false,
      active: false,
    },
    {
      id: 49,
      catId: 2,
      name: 'Eared Coneflower',
      description: 'ultrices enim lorem ipsum dolor sit',
      image: 'http://dummyimage.com/178x100.png/5fa2dd/ffffff',
      price: 70,
      stock: 20,
      featured: false,
      active: true,
    },
    {
      id: 50,
      catId: 4,
      name: 'Climbing Wartclub',
      description: 'quisque id justo sit amet sapien dignissim',
      image: 'http://dummyimage.com/112x100.png/5fa2dd/ffffff',
      price: 44,
      stock: 46,
      featured: false,
      active: false,
    },
  ];
  constructor() {}
}
