import { Injectable } from '@angular/core';
import { Product } from '../model/product';

@Injectable({
  providedIn: 'root',
})
export class ProductService {
  list: Product[] = [
    {
      id: 1,
      catId: 5,
      name: 'American Gomphillus Lichen',
      description:
        'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',
      image: 'http://dummyimage.com/161x100.png/ff4444/ffffff',
      price: 9336,
      stock: 55,
      featured: true,
      active: true,
    },
    {
      id: 2,
      catId: 6,
      name: "Kindberg's Climacium Moss",
      description:
        'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.',
      image: 'http://dummyimage.com/233x100.png/dddddd/000000',
      price: 5743,
      stock: 6,
      featured: true,
      active: true,
    },
    {
      id: 3,
      catId: 9,
      name: 'Wintergreen Barberry',
      description:
        'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.',
      image: 'http://dummyimage.com/128x100.png/5fa2dd/ffffff',
      price: 1165,
      stock: 2,
      featured: false,
      active: false,
    },
    {
      id: 4,
      catId: 3,
      name: 'Tropical Kudzu',
      description: 'Fusce consequat. Nulla nisl. Nunc nisl.',
      image: 'http://dummyimage.com/240x100.png/dddddd/000000',
      price: 9637,
      stock: 67,
      featured: true,
      active: true,
    },
    {
      id: 5,
      catId: 2,
      name: 'Prairie Gentian',
      description:
        'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.',
      image: 'http://dummyimage.com/232x100.png/5fa2dd/ffffff',
      price: 5546,
      stock: 9,
      featured: false,
      active: true,
    },
    {
      id: 6,
      catId: 6,
      name: 'California Red Fir',
      description:
        'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',
      image: 'http://dummyimage.com/211x100.png/ff4444/ffffff',
      price: 8599,
      stock: 75,
      featured: false,
      active: true,
    },
    {
      id: 7,
      catId: 1,
      name: 'Elongate Dicranum Moss',
      description:
        'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.',
      image: 'http://dummyimage.com/220x100.png/ff4444/ffffff',
      price: 7734,
      stock: 27,
      featured: true,
      active: true,
    },
    {
      id: 8,
      catId: 1,
      name: 'Candle Tree',
      description:
        'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.',
      image: 'http://dummyimage.com/189x100.png/cc0000/ffffff',
      price: 1570,
      stock: 20,
      featured: false,
      active: true,
    },
    {
      id: 9,
      catId: 10,
      name: 'Leechbush',
      description:
        'Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',
      image: 'http://dummyimage.com/203x100.png/ff4444/ffffff',
      price: 8067,
      stock: 6,
      featured: false,
      active: false,
    },
    {
      id: 10,
      catId: 8,
      name: "Pringle's Aster",
      description:
        'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
      image: 'http://dummyimage.com/210x100.png/dddddd/000000',
      price: 537,
      stock: 82,
      featured: true,
      active: false,
    },
    {
      id: 11,
      catId: 4,
      name: "Tracy's Pea",
      description:
        'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',
      image: 'http://dummyimage.com/142x100.png/cc0000/ffffff',
      price: 5630,
      stock: 91,
      featured: false,
      active: false,
    },
    {
      id: 12,
      catId: 8,
      name: 'Silverleaf Ponysfoot',
      description:
        'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.',
      image: 'http://dummyimage.com/192x100.png/5fa2dd/ffffff',
      price: 7986,
      stock: 57,
      featured: true,
      active: true,
    },
    {
      id: 13,
      catId: 3,
      name: 'Arctic Alpine Forget-me-not',
      description:
        'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.',
      image: 'http://dummyimage.com/168x100.png/5fa2dd/ffffff',
      price: 9549,
      stock: 19,
      featured: false,
      active: true,
    },
    {
      id: 14,
      catId: 6,
      name: 'Lecidea Lichen',
      description:
        'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.',
      image: 'http://dummyimage.com/223x100.png/cc0000/ffffff',
      price: 6632,
      stock: 40,
      featured: false,
      active: true,
    },
    {
      id: 15,
      catId: 1,
      name: 'Looseflower Water-willow',
      description:
        'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.',
      image: 'http://dummyimage.com/100x100.png/dddddd/000000',
      price: 9376,
      stock: 15,
      featured: false,
      active: true,
    },
    {
      id: 16,
      catId: 7,
      name: 'Western False Asphodel',
      description:
        'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.',
      image: 'http://dummyimage.com/234x100.png/dddddd/000000',
      price: 8969,
      stock: 43,
      featured: false,
      active: true,
    },
    {
      id: 17,
      catId: 4,
      name: "Burnet's Skin Lichen",
      description:
        'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
      image: 'http://dummyimage.com/240x100.png/ff4444/ffffff',
      price: 4150,
      stock: 22,
      featured: false,
      active: true,
    },
    {
      id: 18,
      catId: 3,
      name: 'Puerto Rico Silver Palm',
      description:
        'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',
      image: 'http://dummyimage.com/135x100.png/cc0000/ffffff',
      price: 4537,
      stock: 58,
      featured: false,
      active: false,
    },
    {
      id: 19,
      catId: 1,
      name: 'Texas Signalgrass',
      description:
        'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.',
      image: 'http://dummyimage.com/214x100.png/dddddd/000000',
      price: 4165,
      stock: 6,
      featured: true,
      active: true,
    },
    {
      id: 20,
      catId: 2,
      name: 'Eared Willow',
      description:
        'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',
      image: 'http://dummyimage.com/244x100.png/ff4444/ffffff',
      price: 132,
      stock: 38,
      featured: false,
      active: true,
    },
    {
      id: 21,
      catId: 10,
      name: 'Maroonspot Calicoflower',
      description:
        'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.',
      image: 'http://dummyimage.com/176x100.png/ff4444/ffffff',
      price: 7539,
      stock: 4,
      featured: false,
      active: true,
    },
    {
      id: 22,
      catId: 4,
      name: "Dyer's Greenweed",
      description:
        'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.',
      image: 'http://dummyimage.com/152x100.png/dddddd/000000',
      price: 7829,
      stock: 47,
      featured: true,
      active: false,
    },
    {
      id: 23,
      catId: 4,
      name: 'Wildparsley',
      description:
        'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.',
      image: 'http://dummyimage.com/144x100.png/ff4444/ffffff',
      price: 1455,
      stock: 32,
      featured: false,
      active: false,
    },
    {
      id: 24,
      catId: 3,
      name: 'Corkbark Fir',
      description:
        'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',
      image: 'http://dummyimage.com/165x100.png/ff4444/ffffff',
      price: 4583,
      stock: 24,
      featured: false,
      active: false,
    },
    {
      id: 25,
      catId: 7,
      name: 'Dicranella Moss',
      description: 'In congue. Etiam justo. Etiam pretium iaculis justo.',
      image: 'http://dummyimage.com/142x100.png/ff4444/ffffff',
      price: 1368,
      stock: 72,
      featured: true,
      active: true,
    },
    {
      id: 26,
      catId: 5,
      name: 'Silvery Sedge',
      description:
        'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.',
      image: 'http://dummyimage.com/208x100.png/dddddd/000000',
      price: 1639,
      stock: 7,
      featured: false,
      active: true,
    },
    {
      id: 27,
      catId: 5,
      name: "Devil's Gut",
      description:
        'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.',
      image: 'http://dummyimage.com/223x100.png/ff4444/ffffff',
      price: 8143,
      stock: 9,
      featured: true,
      active: true,
    },
    {
      id: 28,
      catId: 7,
      name: 'Carolina Bruchia Moss',
      description:
        'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
      image: 'http://dummyimage.com/232x100.png/dddddd/000000',
      price: 6046,
      stock: 40,
      featured: true,
      active: true,
    },
    {
      id: 29,
      catId: 7,
      name: "Weill's Lichenochora Lichen",
      description:
        'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',
      image: 'http://dummyimage.com/243x100.png/ff4444/ffffff',
      price: 4166,
      stock: 38,
      featured: false,
      active: true,
    },
    {
      id: 30,
      catId: 1,
      name: 'Eggyolk Lichen',
      description:
        'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.',
      image: 'http://dummyimage.com/239x100.png/ff4444/ffffff',
      price: 3880,
      stock: 54,
      featured: true,
      active: false,
    },
    {
      id: 31,
      catId: 2,
      name: 'Fewflower Pea',
      description:
        'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',
      image: 'http://dummyimage.com/235x100.png/ff4444/ffffff',
      price: 3490,
      stock: 53,
      featured: true,
      active: false,
    },
    {
      id: 32,
      catId: 6,
      name: 'Pink Campion',
      description:
        'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
      image: 'http://dummyimage.com/127x100.png/dddddd/000000',
      price: 3807,
      stock: 21,
      featured: true,
      active: false,
    },
    {
      id: 33,
      catId: 1,
      name: "Kay's Grama",
      description:
        'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.',
      image: 'http://dummyimage.com/206x100.png/5fa2dd/ffffff',
      price: 2543,
      stock: 80,
      featured: false,
      active: true,
    },
    {
      id: 34,
      catId: 3,
      name: "Malme's Chiodecton Lichen",
      description:
        'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',
      image: 'http://dummyimage.com/102x100.png/ff4444/ffffff',
      price: 373,
      stock: 63,
      featured: true,
      active: false,
    },
    {
      id: 35,
      catId: 8,
      name: 'Hairy Gumweed',
      description:
        'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',
      image: 'http://dummyimage.com/237x100.png/5fa2dd/ffffff',
      price: 4652,
      stock: 31,
      featured: false,
      active: true,
    },
    {
      id: 36,
      catId: 3,
      name: 'Garlicvine',
      description:
        'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      image: 'http://dummyimage.com/120x100.png/ff4444/ffffff',
      price: 759,
      stock: 53,
      featured: false,
      active: true,
    },
    {
      id: 37,
      catId: 1,
      name: 'Pygmy Fringetree',
      description:
        'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.',
      image: 'http://dummyimage.com/110x100.png/dddddd/000000',
      price: 7431,
      stock: 88,
      featured: true,
      active: true,
    },
    {
      id: 38,
      catId: 7,
      name: 'Coast Range False Bindweed',
      description:
        'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',
      image: 'http://dummyimage.com/142x100.png/dddddd/000000',
      price: 4366,
      stock: 24,
      featured: true,
      active: false,
    },
    {
      id: 39,
      catId: 5,
      name: "King's Campion",
      description:
        'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',
      image: 'http://dummyimage.com/145x100.png/5fa2dd/ffffff',
      price: 1456,
      stock: 16,
      featured: true,
      active: true,
    },
    {
      id: 40,
      catId: 9,
      name: 'Oregon Checkerbloom',
      description:
        'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.',
      image: 'http://dummyimage.com/192x100.png/ff4444/ffffff',
      price: 3907,
      stock: 16,
      featured: false,
      active: true,
    },
    {
      id: 41,
      catId: 1,
      name: 'Desert Unicorn-plant',
      description:
        'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.',
      image: 'http://dummyimage.com/160x100.png/dddddd/000000',
      price: 4698,
      stock: 72,
      featured: false,
      active: true,
    },
    {
      id: 42,
      catId: 4,
      name: 'Loulu',
      description:
        'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',
      image: 'http://dummyimage.com/134x100.png/ff4444/ffffff',
      price: 1833,
      stock: 29,
      featured: false,
      active: true,
    },
    {
      id: 43,
      catId: 8,
      name: 'Pitcherplant',
      description:
        'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',
      image: 'http://dummyimage.com/129x100.png/ff4444/ffffff',
      price: 5723,
      stock: 3,
      featured: false,
      active: false,
    },
    {
      id: 44,
      catId: 7,
      name: "Sherring's Dwarf Polypody",
      description:
        'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',
      image: 'http://dummyimage.com/142x100.png/cc0000/ffffff',
      price: 6606,
      stock: 82,
      featured: true,
      active: false,
    },
    {
      id: 45,
      catId: 5,
      name: 'Cascade Lily',
      description:
        'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
      image: 'http://dummyimage.com/250x100.png/dddddd/000000',
      price: 1747,
      stock: 75,
      featured: false,
      active: false,
    },
    {
      id: 46,
      catId: 10,
      name: 'Speargrass',
      description:
        'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',
      image: 'http://dummyimage.com/100x100.png/cc0000/ffffff',
      price: 313,
      stock: 16,
      featured: false,
      active: false,
    },
    {
      id: 47,
      catId: 4,
      name: 'Loquat',
      description:
        'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.',
      image: 'http://dummyimage.com/164x100.png/cc0000/ffffff',
      price: 1696,
      stock: 89,
      featured: false,
      active: true,
    },
    {
      id: 48,
      catId: 4,
      name: 'Spiny Greasebush',
      description:
        'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.',
      image: 'http://dummyimage.com/143x100.png/5fa2dd/ffffff',
      price: 7104,
      stock: 60,
      featured: false,
      active: false,
    },
    {
      id: 49,
      catId: 9,
      name: 'False Indigo Bush',
      description:
        'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.',
      image: 'http://dummyimage.com/191x100.png/ff4444/ffffff',
      price: 9467,
      stock: 24,
      featured: true,
      active: true,
    },
    {
      id: 50,
      catId: 1,
      name: 'Bristleleaf Bulrush',
      description:
        'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.',
      image: 'http://dummyimage.com/242x100.png/cc0000/ffffff',
      price: 5435,
      stock: 27,
      featured: false,
      active: false,
    },
    {
      id: 51,
      catId: 6,
      name: 'Prairie Plantain',
      description:
        'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.',
      image: 'http://dummyimage.com/225x100.png/cc0000/ffffff',
      price: 2305,
      stock: 93,
      featured: false,
      active: true,
    },
    {
      id: 52,
      catId: 3,
      name: 'Colorado Spiny Milkvetch',
      description:
        'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      image: 'http://dummyimage.com/125x100.png/5fa2dd/ffffff',
      price: 2122,
      stock: 56,
      featured: true,
      active: true,
    },
    {
      id: 53,
      catId: 5,
      name: "'ohi'a Lehua",
      description:
        'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',
      image: 'http://dummyimage.com/244x100.png/cc0000/ffffff',
      price: 8051,
      stock: 33,
      featured: false,
      active: false,
    },
    {
      id: 54,
      catId: 1,
      name: 'Grass Pea',
      description:
        'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.',
      image: 'http://dummyimage.com/227x100.png/ff4444/ffffff',
      price: 2338,
      stock: 29,
      featured: true,
      active: true,
    },
    {
      id: 55,
      catId: 9,
      name: 'Sweet Vernalgrass',
      description:
        'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
      image: 'http://dummyimage.com/119x100.png/ff4444/ffffff',
      price: 2166,
      stock: 3,
      featured: true,
      active: true,
    },
    {
      id: 56,
      catId: 2,
      name: 'Green Sotol',
      description:
        'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.',
      image: 'http://dummyimage.com/168x100.png/cc0000/ffffff',
      price: 6593,
      stock: 62,
      featured: true,
      active: false,
    },
    {
      id: 57,
      catId: 3,
      name: "Parlin's Dewberry",
      description:
        'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',
      image: 'http://dummyimage.com/204x100.png/dddddd/000000',
      price: 5901,
      stock: 95,
      featured: false,
      active: true,
    },
    {
      id: 58,
      catId: 4,
      name: 'Prairie Rosinweed',
      description:
        'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',
      image: 'http://dummyimage.com/131x100.png/cc0000/ffffff',
      price: 8824,
      stock: 19,
      featured: true,
      active: true,
    },
    {
      id: 59,
      catId: 7,
      name: "Torrey's Blue Eyed Mary",
      description:
        'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.',
      image: 'http://dummyimage.com/133x100.png/dddddd/000000',
      price: 2144,
      stock: 71,
      featured: true,
      active: true,
    },
    {
      id: 60,
      catId: 5,
      name: 'Trans-pecos Stinkleaf',
      description:
        'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',
      image: 'http://dummyimage.com/241x100.png/5fa2dd/ffffff',
      price: 1169,
      stock: 82,
      featured: true,
      active: true,
    },
    {
      id: 61,
      catId: 2,
      name: 'Cochise Beardtongue',
      description:
        'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.',
      image: 'http://dummyimage.com/233x100.png/ff4444/ffffff',
      price: 1870,
      stock: 88,
      featured: true,
      active: true,
    },
    {
      id: 62,
      catId: 4,
      name: 'Devilshead',
      description:
        'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',
      image: 'http://dummyimage.com/211x100.png/cc0000/ffffff',
      price: 405,
      stock: 9,
      featured: false,
      active: true,
    },
    {
      id: 63,
      catId: 9,
      name: 'Dwarf Muellerella Lichen',
      description:
        'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.',
      image: 'http://dummyimage.com/225x100.png/ff4444/ffffff',
      price: 1513,
      stock: 25,
      featured: false,
      active: true,
    },
    {
      id: 64,
      catId: 3,
      name: 'Blue Creek Stonecrop',
      description:
        'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.',
      image: 'http://dummyimage.com/123x100.png/ff4444/ffffff',
      price: 5890,
      stock: 22,
      featured: false,
      active: false,
    },
    {
      id: 65,
      catId: 8,
      name: 'Capitate Sedge',
      description:
        'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',
      image: 'http://dummyimage.com/135x100.png/ff4444/ffffff',
      price: 9118,
      stock: 16,
      featured: false,
      active: true,
    },
    {
      id: 66,
      catId: 1,
      name: "Wright's Flowering Fern",
      description:
        'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',
      image: 'http://dummyimage.com/241x100.png/cc0000/ffffff',
      price: 9654,
      stock: 16,
      featured: false,
      active: true,
    },
    {
      id: 67,
      catId: 10,
      name: 'Indian Anoda',
      description:
        'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',
      image: 'http://dummyimage.com/163x100.png/5fa2dd/ffffff',
      price: 5203,
      stock: 99,
      featured: false,
      active: true,
    },
    {
      id: 68,
      catId: 6,
      name: 'Tushar Range Beardtongue',
      description:
        'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',
      image: 'http://dummyimage.com/243x100.png/5fa2dd/ffffff',
      price: 3674,
      stock: 97,
      featured: false,
      active: true,
    },
    {
      id: 69,
      catId: 10,
      name: 'Arizona Cypress',
      description:
        'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.',
      image: 'http://dummyimage.com/216x100.png/ff4444/ffffff',
      price: 6931,
      stock: 89,
      featured: false,
      active: true,
    },
    {
      id: 70,
      catId: 5,
      name: 'Whitethorn Acacia',
      description: 'Fusce consequat. Nulla nisl. Nunc nisl.',
      image: 'http://dummyimage.com/154x100.png/5fa2dd/ffffff',
      price: 7843,
      stock: 94,
      featured: false,
      active: false,
    },
    {
      id: 71,
      catId: 7,
      name: 'Splitbeard Bluestem',
      description:
        'Phasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',
      image: 'http://dummyimage.com/136x100.png/ff4444/ffffff',
      price: 5340,
      stock: 35,
      featured: false,
      active: true,
    },
    {
      id: 72,
      catId: 2,
      name: 'Quillwort',
      description:
        'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',
      image: 'http://dummyimage.com/134x100.png/5fa2dd/ffffff',
      price: 6486,
      stock: 43,
      featured: true,
      active: false,
    },
    {
      id: 73,
      catId: 8,
      name: 'Piedmont Mock Bishopweed',
      description:
        'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.',
      image: 'http://dummyimage.com/163x100.png/cc0000/ffffff',
      price: 6396,
      stock: 87,
      featured: true,
      active: true,
    },
    {
      id: 74,
      catId: 3,
      name: "Thurber's Morning-glory",
      description:
        'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
      image: 'http://dummyimage.com/133x100.png/ff4444/ffffff',
      price: 2259,
      stock: 92,
      featured: true,
      active: true,
    },
    {
      id: 75,
      catId: 5,
      name: 'Shaggytuft',
      description:
        'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.',
      image: 'http://dummyimage.com/150x100.png/cc0000/ffffff',
      price: 4981,
      stock: 88,
      featured: false,
      active: false,
    },
    {
      id: 76,
      catId: 7,
      name: 'Longleaf Pondweed',
      description:
        'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.',
      image: 'http://dummyimage.com/120x100.png/dddddd/000000',
      price: 5407,
      stock: 16,
      featured: false,
      active: true,
    },
    {
      id: 77,
      catId: 2,
      name: 'Sickle Kiaeria Moss',
      description:
        'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
      image: 'http://dummyimage.com/157x100.png/5fa2dd/ffffff',
      price: 7868,
      stock: 63,
      featured: true,
      active: false,
    },
    {
      id: 78,
      catId: 8,
      name: "Orcutt's Yellow Pincushion",
      description:
        'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.',
      image: 'http://dummyimage.com/165x100.png/ff4444/ffffff',
      price: 3636,
      stock: 30,
      featured: true,
      active: false,
    },
    {
      id: 79,
      catId: 8,
      name: 'Slender-fruit Beaksedge',
      description:
        'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.',
      image: 'http://dummyimage.com/135x100.png/ff4444/ffffff',
      price: 6954,
      stock: 42,
      featured: false,
      active: false,
    },
    {
      id: 80,
      catId: 2,
      name: 'Hemlock',
      description:
        'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.',
      image: 'http://dummyimage.com/118x100.png/5fa2dd/ffffff',
      price: 6782,
      stock: 95,
      featured: false,
      active: true,
    },
    {
      id: 81,
      catId: 10,
      name: "California Stork's Bill",
      description:
        'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
      image: 'http://dummyimage.com/165x100.png/5fa2dd/ffffff',
      price: 9871,
      stock: 50,
      featured: false,
      active: true,
    },
    {
      id: 82,
      catId: 4,
      name: 'Mountain Ricegrass',
      description:
        'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
      image: 'http://dummyimage.com/147x100.png/5fa2dd/ffffff',
      price: 4926,
      stock: 85,
      featured: false,
      active: true,
    },
    {
      id: 83,
      catId: 2,
      name: 'Brookfoam',
      description:
        'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',
      image: 'http://dummyimage.com/123x100.png/cc0000/ffffff',
      price: 5703,
      stock: 27,
      featured: false,
      active: false,
    },
    {
      id: 84,
      catId: 2,
      name: 'Ogilvie Range Draba',
      description:
        'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',
      image: 'http://dummyimage.com/150x100.png/cc0000/ffffff',
      price: 8372,
      stock: 72,
      featured: false,
      active: false,
    },
    {
      id: 85,
      catId: 2,
      name: 'Protea',
      description:
        'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.',
      image: 'http://dummyimage.com/156x100.png/dddddd/000000',
      price: 9323,
      stock: 57,
      featured: true,
      active: true,
    },
    {
      id: 86,
      catId: 1,
      name: 'Rock Buckthorn',
      description:
        'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.',
      image: 'http://dummyimage.com/194x100.png/ff4444/ffffff',
      price: 483,
      stock: 81,
      featured: false,
      active: false,
    },
    {
      id: 87,
      catId: 10,
      name: "Shriver's Purple Fringed Orchid",
      description:
        'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',
      image: 'http://dummyimage.com/224x100.png/cc0000/ffffff',
      price: 3164,
      stock: 2,
      featured: true,
      active: true,
    },
    {
      id: 88,
      catId: 7,
      name: 'Whitebristle Cottongrass',
      description:
        'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.',
      image: 'http://dummyimage.com/202x100.png/dddddd/000000',
      price: 5702,
      stock: 66,
      featured: false,
      active: false,
    },
    {
      id: 89,
      catId: 2,
      name: 'San Bernardino Spineflower',
      description:
        'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.',
      image: 'http://dummyimage.com/100x100.png/5fa2dd/ffffff',
      price: 2169,
      stock: 34,
      featured: false,
      active: false,
    },
    {
      id: 90,
      catId: 6,
      name: 'Sonoran Silverbush',
      description:
        'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',
      image: 'http://dummyimage.com/231x100.png/cc0000/ffffff',
      price: 7437,
      stock: 82,
      featured: false,
      active: false,
    },
    {
      id: 91,
      catId: 9,
      name: 'Greenstar Sedge',
      description:
        'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',
      image: 'http://dummyimage.com/110x100.png/dddddd/000000',
      price: 6515,
      stock: 3,
      featured: true,
      active: true,
    },
    {
      id: 92,
      catId: 9,
      name: 'Rim Lichen',
      description: 'In congue. Etiam justo. Etiam pretium iaculis justo.',
      image: 'http://dummyimage.com/236x100.png/ff4444/ffffff',
      price: 1804,
      stock: 53,
      featured: false,
      active: false,
    },
    {
      id: 93,
      catId: 8,
      name: "Henderson's Angelica",
      description:
        'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.',
      image: 'http://dummyimage.com/114x100.png/5fa2dd/ffffff',
      price: 4273,
      stock: 59,
      featured: true,
      active: false,
    },
    {
      id: 94,
      catId: 5,
      name: 'Tumamoc Globeberry',
      description:
        'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
      image: 'http://dummyimage.com/159x100.png/5fa2dd/ffffff',
      price: 6083,
      stock: 94,
      featured: true,
      active: false,
    },
    {
      id: 95,
      catId: 4,
      name: 'Crossidium Moss',
      description:
        'Phasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',
      image: 'http://dummyimage.com/222x100.png/dddddd/000000',
      price: 8376,
      stock: 60,
      featured: true,
      active: false,
    },
    {
      id: 96,
      catId: 1,
      name: 'Taiwan Kudzu',
      description:
        'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.',
      image: 'http://dummyimage.com/199x100.png/ff4444/ffffff',
      price: 4235,
      stock: 52,
      featured: false,
      active: false,
    },
    {
      id: 97,
      catId: 9,
      name: 'Wart Lichen',
      description:
        'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.',
      image: 'http://dummyimage.com/200x100.png/ff4444/ffffff',
      price: 3798,
      stock: 97,
      featured: false,
      active: true,
    },
    {
      id: 98,
      catId: 8,
      name: 'Fringed Pink',
      description:
        'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.',
      image: 'http://dummyimage.com/227x100.png/dddddd/000000',
      price: 224,
      stock: 55,
      featured: false,
      active: false,
    },
    {
      id: 99,
      catId: 1,
      name: 'Cow Soapwort',
      description:
        'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.',
      image: 'http://dummyimage.com/145x100.png/cc0000/ffffff',
      price: 7745,
      stock: 23,
      featured: false,
      active: false,
    },
    {
      id: 100,
      catId: 5,
      name: 'Sickle Kiaeria Moss',
      description:
        'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',
      image: 'http://dummyimage.com/187x100.png/5fa2dd/ffffff',
      price: 5266,
      stock: 19,
      featured: true,
      active: true,
    },
  ];
  constructor() {}
}
